# -*- mode: org; coding: utf-8; -*-
# Time-stamp: <2017-11-07 21:48:25 krylon>


* kryLisp
** README
   Somebody much wiser than me once said:
   "Any sufficiently complicated C or Fortran program contains an
   ad-hoc, informally-specified, bug-ridden, slow implementation of
   half of Common Lisp."

   Somebody else, also wiser than me, added:
   "...including Common Lisp."

   So yeah, here we are. This is the mandatory toy Lisp interpreter
   everyone tries to build once in their lifetime.
   It takes ideas ideas both from Common Lisp and from Scheme, puts
   them together in a bag and beats the ____ out of them with a
   baseball bat.

   This interpreter was mainly written as an excercise to learn about
   the challenges and pitfalls one encounters when building an
   interpreter for a custom programming language - Lisp being the
   simplest possible case, where the syntax is concerned -, and my
   main goal was to learn something, not to build a great piece of
   software. Not even to build a halfway decent piece of software.

   So if you look over this and think "Man, this sucks really hard",
   you are most likely right.

   If you want to help me make this suck slightly less hard, patches
   are thoughtfully considered. ;-)
** Parser
   Ich dachte erst, ich könnte ja beim Parser aus dem
   Go-Interpreterbuch abgucken, aber der ist für die simple Syntax,
   die Lisp braucht, eigentlich schon wieder overkill.
   Ich hatte ja schon mal einen Lisp-Interpreter in Python
   geschrieben, der funktionierte grundsätzlich gut.
   Aber da gab es auch eine sehr gute Bibliothek zum Bau von Parsern.
   In Go gibt es in der Standardbibliothek den ganzen Kram, den wohl
   auch der Go-Compiler benutzt, aber das wird entsprechend auch sehr
   Go-spezifisch sein.
   Es gibt ja auch _gocc_, das ist wohl grob äquivalent zu bison für C.
   Oder _ANTLR_. Aber das ist doch eigentlich alle overkill, oder?
   Eventuell kann ich auch mal PEG ausprobieren.
*** gocc
    Ich probiere jetzt erstmal gocc aus, das macht so beim Lesen der
    Doku einen guten Eindruck. Hat nur das Problem, das ich für die
    BNF-Dateien, die ich dafür schreiben muss, keine
    Syntax-Unterstützung von Emacs habe.
**** [2017-10-19 Do 17:39]
     gocc funktioniert für meine Anforderungen gut, solange ich keinen
     gewichtigen Grund finde, bleibe ich dabei. 
*** Funktionen
    [2017-09-10 So 02:53]
    Ich habe nach einigem Nachdenken beschlossen, Funktionen einen
    eigenen Datentypen zu geben, aber jetzt frage ich mich, an welcher
    Stelle aus einer Liste eine Funktion wird.
    Mein erster Gedanke war das im Parser unterzubringen, aber das
    wird nichts.
    Dann fiel mir ein, dass ich ja zumindest mittelfristig das Ziel
    habe Makros in den Interpreter einzubauen, und damit die sinnvoll
    sind, muss ich einmal am Anfang den AST abklappern und alle Makros
    expandieren.
    Bei der Gelegenheit könnte ich dann auch Lambda-Listen durch
    Funktions-Objekte ersetzen.
    Das klingt nach einer vernünftigen Idee. Womöglich kann ich auf
    dem Wege auch ein paar Optimierungen einbauen? Irgendwann mal.
** Interpreter
*** [2017-10-02 Mo 21:12] Lisp-1 vs. Lisp-2
    Allmählich verstehe ich diese Bemerkung von Kent Pitman, oder wem
    auch immer, über Lisp-1 vs. Lisp-2 Sprachen besser und frage mich
    langsam, ob ich mir den Scheiß antun will, einen Lisp-2-Dialekt zu
    erschaffen. Der Hauptvorteil ist, dass man eine Funktion list und
    eine lokale Variable list haben kann, was bei Funktionen wie
    mapcar und Freunden die Lesbarkeit etwas steigert.
    Der Performance-Vorteil ist in meinem Fall vermutlich irrelevant.
    Ich probiere es erstmal weiter als Lisp-2, und wenn mir das
    irgendwann zu haarig wird, muss ich noch mal schauen, in der
    naiven Hoffnung, dass ich mir bis dahin nicht zu sehr in den Fuß
    geschossen habe.
    Andererseits brauche ich ja zumindest für Makros noch einen
    weiteren Namespace... oder? Eigentlich nicht. Ist zumindest keine
    gute Idee, ich müsste klare Regeln definieren, wann ein Symbol
    eine Funktion oder ein Makro meint. Außer bei Sachen wie
    MACROEXPAND ist das so gut wie nie der Fall, glaube ich. :-/
*** [2017-09-23 Sa 14:22]
    Allmählich nähert sich der Interpreter dem Punkt, an dem er auf
    der theoretischen, abstrakten Ebene halbwegs vollständig ist.
    Ein bisschen boolsche Logik brauche ich noch.
*** [2017-10-19 Do 17:37]
    Ich habe inzwischen den Interpreter so weit, dass ein erstes
    einfaches Test-Script läuft.
    Jetzt kann ich mich nach der langen Debugging-Orgie also wieder
    daran setzen, Features hinzuzufügen.
    Makros? Richtige Zahlen? I/O? Datenstrukturen und Collections?
    Ich sollte mir das mal notieren
*** [2017-11-03 Fr 18:46]
    Arithmetik funktioniert jetzt *ungefähr* so, wie ich mir das vorstelle.
    Integer-Werte werden automatisch in big.Int und in64 konvertiert,
    je nachdem, wie groß der Wert ist.
    Als nächstes möchte ich mehr Datentypen hinzufügen und Funktionen,
    um das ordentlich zu supporten.
    Ich fange an mit Strings und regulären Ausdrücken.
*** [2017-11-03 Fr 20:33]
    Es stellt sich heraus, dass ich für reguläre Ausdrücke entweder
    einen dedizierten Match-Typen brauche, oder ein Array.
    Also füge ich erstmal Arrays und Hashtables hinzu.
    Und wo ich dabei bin, Schleifen wären nett. Bislang geht das nur
    über Rekursion, und ich mache (bislang) keinen Versuch
    Endrekursion wegzuoptimieren.
*** [2017-11-04 Sa 23:58]
    Okay, Arrays und Hashtables scheinen - mit sehr oberflächlichen
    Tests! - zu funktionieren.
    Dann wird es wohl langsam Zeit für Makros, right?
    Das wird kein Spaß.
** Aufgaben
*** TODO [#A] Makros
*** DONE [#A] Zahlen
    CLOSED: [2017-11-03 Fr 18:45]
    Ich will gern bignum-Support und Support für Floating Point,
    eventuell, wenn es nicht zu haarig ist, auch Support für rationale
    und vielleicht für komplexe Zahlen.
*** TODO [#B] I/O
    Ist auf Dauer blöd, wenn das nicht geht.
**** [2017-11-07 Di 21:15]
     Okay, allmählich habe ich die Grundlagen so weit, dass ich I/O
     implementieren könnte. Glaube ich jedenfalls.
     Aber wenn ich das gut machen will, wird es nicht ganz
     einfach. Ich würde am liebsten einen Weg ähnlich wie Go
     einschlagen, und Reader und Writer haben, bei denen erstmal keine
     Rolle spielt, ob das Dateien, Netzwerkverbindungen, oder was auch
     immer sind.
*** TODO [#C] Datenstrukturen und Collections
**** [2017-11-07 Di 21:16]
     Arrays und Hashtables habe ich inzwischen umgesetzt, structs aber
     noch nicht.
*** TODO Schleifen
    Ich will gern richtige Iteration haben, weil ich keine Lust habe
    mich zu informieren, wie ich Endrekursion weg optimiere.
    Ich hätte gern eine Art foreach-Konstrukt, will aber, dass das
    erweiterbar bleibt. Da schreibe ich für den Anfang vielleicht
    erstmal Test-Code und schaue dann, wie ich das zum Laufen
    bekomme. 
**** [2017-11-06 Mo 21:46]
     Wenn ich so darüber nachdenke, will ich zwei
     Schleifen-Konstrukte, eins um über eine Collection von Sachen
     drüber zu eiern, und eins für den Menschen, der schon alles hat.
     Dann brauche ich aber immer noch mein Gegenstück zu Python's
     Iterator-Protokoll.
     Dann müsste ich ja sowas wie Multi-Methods / Multi-Dispatch drauf
     haben.
     Oder ich mache das _sehr_ minimalistisch und sage, man muss nur
     zwei Funktionen übergeben, eine, die sagt, ob ich am Ende bin,
     und eine, die mich einen Platz vorrücken lässt und mir das
     aktuelle Element gibt. Aber das klingt etwas ... optimistisch.
**** [2017-11-07 Di 21:08]
     Eine DO-Schleife, deren Syntax und Semantik ich weitgehend bei
     Common Lisp abgekupfert habe, habe ich beisammen, und der einsame
     Test, den ich dafür geschrieben habe, läuft auch.
     Jetzt stellt sich die Frage, will ich immer noch ein FOREACH
     bauen?
     Mmmh, ich glaube, ich will erstmal Makros implementieren.
     Vielleicht kann ich dann ja FOREACH als Makro umsetzen?
     Und vielleicht wäre es allmählich an der Zeit, ein paar
     Benchmarks zu schreiben?
     Aber Moment! Mir fehlt noch etwas Wichtiges, nämlich I/O! Das
     könnte auch ein bisschen knifflig werden... 
*** TODO Testen
    Das schöne an einem Interpreter für eine Programmiersprache, ist
    dass es relativ gesehen /sehr/ einfach ist, alle möglichen Aspekte
    isoliert durch zu testen.
    Darum mache ich von der Möglichkeit regen Gebrauch und versuche
    auch wo immer es geht table-driven-testing zu praktizieren. In ein
    paar Fällen hat sich das auch schon rentiert, z.B. als ich neue
    numerische Typen hinzugefügt habe - neue Tests für alle möglichen
    Konstellationen hinzuzufügen war ziemlich trivial.
**** TODO [#A] Fuzzing
     Fuzzing ist ja der zeit der heiße Scheiß. Und das Schicksal es
     will, gibt es auch für Go eine Fuzzing-Bibliothek. Ich würde gern
     versuchen die zu benutzen, um meinen Parser/Interpreter noch
     brutaler zu testen.
     Und Fuzzer haben ja offenbar einen sehr guten Track Record bei
     großen Codebasen subtile Bugs aufzuspüren, die auch
     hochkompetenten und sehr erfahrenen Programmier_innen nicht ins
     Auge gestochen sind. 
