/* Time-stamp: <2017-09-07 20:37:57 krylon>
 * Lexical elements
 *
 * Mittwoch, 06. 09. 2017, 13:49
 * Ein Vorteil von Lisp ist, dass die Syntax so einfach ist.
 * Wenn ich Makros einbauen will, wird es ein wenig komplexer,
 * aber eins nach dem Anderen.
 */

_digit : '0'-'9' ;
integer : '1'-'9' {_digit} ;

lparen : '(' ;
rparen : ')' ;

apostrophe : '\'';

_letter : 'a'-'z' | 'A'-'Z' | 'ä' | 'ö' | 'ü' | 'Ä' | 'Ö' | 'Ü' | 'ß' ;

_symbolchar : _letter | ':' | '_' | '-' | '+' | '-' | '*' | '%' | '!' | '?' | 
             '/' | '$' | '=' ;

symbol : _symbolchar {_symbolchar} ;

string : '"' {.} '"' ;

// _atom: _number | _symbol | _string ;

!whitespace : ' ' | '\t' | '\n' | '\r' ;

!comment : ';' {.} '\n' ;

/* Syntax elements */

<<
        import (
               "krylisp/token"
               "krylisp/value"
               pu "krylisp/parserutil"
               "strings"
        )
>>

Number
        : integer                               << pu.IntValue($0.(*token.Token).Lit) >>
        ;

String 
       : string                                << value.StringValue($0.(*token.Token).Lit) >>
       ;

Symbol 
       : symbol                                << value.Symbol(strings.ToUpper($0.(*token.Token).Lit)) >>
       ;

Atom
        : Number
        | String
        | Symbol
        ;

// Mittwoch, 06. 09. 2017, 17:06
// Listen könnte ich schon direkt hier in Cons-Listen parsen.
// Aber ich muss noch einen Datentyp dafür definieren. :-|

Expression
        : List
        | Atom
        | apostrophe Expression
        ;

List
        : lparen ListBody rparen << &value.List{ Car: $1 } >>
        ;

ListBody
        : Expression                    << &value.ConsCell{ Car: $0 } >>
        | Expression ListBody           << &value.ConsCell{ Car: $0, Cdr: $1 } >>
        ;

Program
        : Expression
        | Expression Program
        ;
