# -*- mode: org; coding: utf-8; -*-
# Time-stamp: <2017-10-02 21:15:15 krylon>


* kryLisp
** Parser
   Ich dachte erst, ich könnte ja beim Parser aus dem
   Go-Interpreterbuch abgucken, aber der ist für die simple Syntax,
   die Lisp braucht, eigentlich schon wieder overkill.
   Ich hatte ja schon mal einen Lisp-Interpreter in Python
   geschrieben, der funktionierte grundsätzlich gut.
   Aber da gab es auch eine sehr gute Bibliothek zum Bau von Parsern.
   In Go gibt es in der Standardbibliothek den ganzen Kram, den wohl
   auch der Go-Compiler benutzt, aber das wird entsprechend auch sehr
   Go-spezifisch sein.
   Es gibt ja auch _gocc_, das ist wohl grob äquivalent zu bison für C.
   Oder _ANTLR_. Aber das ist doch eigentlich alle overkill, oder?
   Eventuell kann ich auch mal PEG ausprobieren.
*** gocc
    Ich probiere jetzt erstmal gocc aus, das macht so beim Lesen der
    Doku einen guten Eindruck. Hat nur das Problem, das ich für die
    BNF-Dateien, die ich dafür schreiben muss, keine
    Syntax-Unterstützung von Emacs habe.
*** Funktionen
    [2017-09-10 So 02:53]
    Ich habe nach einigem Nachdenken beschlossen, Funktionen einen
    eigenen Datentypen zu geben, aber jetzt frage ich mich, an welcher
    Stelle aus einer Liste eine Funktion wird.
    Mein erster Gedanke war das im Parser unterzubringen, aber das
    wird nichts.
    Dann fiel mir ein, dass ich ja zumindest mittelfristig das Ziel
    habe Makros in den Interpreter einzubauen, und damit die sinnvoll
    sind, muss ich einmal am Anfang den AST abklappern und alle Makros
    expandieren.
    Bei der Gelegenheit könnte ich dann auch Lambda-Listen durch
    Funktions-Objekte ersetzen.
    Das klingt nach einer vernünftigen Idee. Womöglich kann ich auf
    dem Wege auch ein paar Optimierungen einbauen? Irgendwann mal.
** Interpreter
*** [2017-10-02 Mo 21:12] Lisp-1 vs. Lisp-2
    Allmählich verstehe ich diese Bemerkung von Kent Pitman, oder wem
    auch immer, über Lisp-1 vs. Lisp-2 Sprachen besser und frage mich
    langsam, ob ich mir den Scheiß antun will, einen Lisp-2-Dialekt zu
    erschaffen. Der Hauptvorteil ist, dass man eine Funktion list und
    eine lokale Variable list haben kann, was bei Funktionen wie
    mapcar und Freunden die Lesbarkeit etwas steigert.
    Der Performance-Vorteil ist in meinem Fall vermutlich irrelevant.
    Ich probiere es erstmal weiter als Lisp-2, und wenn mir das
    irgendwann zu haarig wird, muss ich noch mal schauen, in der
    naiven Hoffnung, dass ich mir bis dahin nicht zu sehr in den Fuß
    geschossen habe.
    Andererseits brauche ich ja zumindest für Makros noch einen
    weiteren Namespace... oder? Eigentlich nicht. Ist zumindest keine
    gute Idee, ich müsste klare Regeln definieren, wann ein Symbol
    eine Funktion oder ein Makro meint. Außer bei Sachen wie
    MACROEXPAND ist das so gut wie nie der Fall, glaube ich. :-/
*** [2017-09-23 Sa 14:22]
    Allmählich nähert sich der Interpreter dem Punkt, an dem er auf
    der theoretischen, abstrakten Ebene halbwegs vollständig ist.
    Ein bisschen boolsche Logik brauche ich noch.
