/* Time-stamp: <2017-10-26 13:42:14 krylon>
 * Lexical elements
 *
 * Mittwoch, 06. 09. 2017, 13:49
 * Ein Vorteil von Lisp ist, dass die Syntax so einfach ist.
 * Wenn ich Makros einbauen will, wird es ein wenig komplexer,
 * aber eins nach dem Anderen.
 */

_digit : '0'-'9' ;
integer : '0' | '1'-'9' {_digit} ;

_dot: '.' ;

float: _digit {_digit} _dot _digit {_digit} 
     | _digit {_digit} 'f' ;

bignum: _digit {_digit} 'b' ;

lparen : '(' ;
rparen : ')' ;

apostrophe : '\'';
_doubleQuote : '"';

hash : '#';

_letter : 'a'-'z' | 'A'-'Z' | 'ä' | 'ö' | 'ü' | 'Ä' | 'Ö' | 'Ü' | 'ß' ;

_symbolchar : _letter | ':' | '_' | '-' | '+' | '-' | '*' | '%' | '!' | '?' | '/' | '$' | '=' | '~' | '<' | '>' ;

/* _symchar_or_digit: _symbolchar | _digit; */

symbol : _symbolchar {_symbolchar} ;

string :  _doubleQuote {.} _doubleQuote ;

!whitespace : ' ' | '\t' | '\n' | '\r' ;

!comment : ';' {.} '\n' ;

/* Syntax elements */

<<
        import (
               "krylisp/token"
               "krylisp/value"
               pu "krylisp/parserutil"
               "strings"
        )
>>

Program
        : Expression                    << []value.LispValue{ $0.(value.LispValue) }, nil >>
        | Program Expression            << append($0.([]value.LispValue), $1.(value.LispValue)), nil >>
        ;

Expression
        : List
        | Atom
        | apostrophe Expression                << &value.List{
                                                        Car: &value.ConsCell{
                                                             Car: value.Symbol("QUOTE"),
                                                             Cdr: &value.ConsCell{
                                                                  Car: $1.(value.LispValue),
                                                                  Cdr: nil,
                                                             },
                                                        },
                                                        Length: 2,
                                                  }, nil
                                                >>
        | hash Symbol                           << &value.List{
                                                        Car: &value.ConsCell{
                                                             Car: value.Symbol("FN"),
                                                             Cdr: &value.ConsCell{
                                                                  Car: $1.(value.Symbol),
                                                                  Cdr: nil,
                                                             },
                                                        },
                                                        Length: 2,
                                                   }, nil
                                                >>
        ;

Atom
        : Number
        | String
        | Symbol ;

Number
        : integer                               << pu.IntValue(string($0.(*token.Token).Lit)), nil >>
        | float                                 << pu.FloatValue(string($0.(*token.Token).Lit)), nil >>
        | bignum                                << pu.Bignum(string($0.(*token.Token).Lit)), nil >>
        ;

String 
       : string                                << pu.StringValue($0.(*token.Token).Lit), nil >>
       ;

Symbol 
       : symbol                                << value.Symbol(strings.ToUpper(string($0.(*token.Token).Lit))), nil >>
       ;

List
        : lparen ListBody rparen        << &value.List{ Car: $1.(*value.ConsCell), Length: $1.(*value.ConsCell).ActualLength() }, nil >>
        | lparen rparen                 << &value.List{ Car: nil, Length: 0 }, nil >>
        ;

ListBody
        : Expression                    << &value.ConsCell{ Car: $0.(value.LispValue) }, nil >>
        | Expression ListBody           << &value.ConsCell{ Car: $0.(value.LispValue), Cdr: $1.(*value.ConsCell) }, nil >>
        ;

