# -*- mode: org; coding: utf-8; -*-
# Time-stamp: <2017-09-10 02:57:05 krylon>


* kryLisp
** Parser
   Ich dachte erst, ich könnte ja beim Parser aus dem
   Go-Interpreterbuch abgucken, aber der ist für die simple Syntax,
   die Lisp braucht, eigentlich schon wieder overkill.
   Ich hatte ja schon mal einen Lisp-Interpreter in Python
   geschrieben, der funktionierte grundsätzlich gut.
   Aber da gab es auch eine sehr gute Bibliothek zum Bau von Parsern.
   In Go gibt es in der Standardbibliothek den ganzen Kram, den wohl
   auch der Go-Compiler benutzt, aber das wird entsprechend auch sehr
   Go-spezifisch sein.
   Es gibt ja auch _gocc_, das ist wohl grob äquivalent zu bison für C.
   Oder _ANTLR_. Aber das ist doch eigentlich alle overkill, oder?
   Eventuell kann ich auch mal PEG ausprobieren.
*** gocc
    Ich probiere jetzt erstmal gocc aus, das macht so beim Lesen der
    Doku einen guten Eindruck. Hat nur das Problem, das ich für die
    BNF-Dateien, die ich dafür schreiben muss, keine
    Syntax-Unterstützung von Emacs habe.
*** Funktionen
    [2017-09-10 So 02:53]
    Ich habe nach einigem Nachdenken beschlossen, Funktionen einen
    eigenen Datentypen zu geben, aber jetzt frage ich mich, an welcher
    Stelle aus einer Liste eine Funktion wird.
    Mein erster Gedanke war das im Parser unterzubringen, aber das
    wird nichts.
    Dann fiel mir ein, dass ich ja zumindest mittelfristig das Ziel
    habe Makros in den Interpreter einzubauen, und damit die sinnvoll
    sind, muss ich einmal am Anfang den AST abklappern und alle Makros
    expandieren.
    Bei der Gelegenheit könnte ich dann auch Lambda-Listen durch
    Funktions-Objekte ersetzen.
    Das klingt nach einer vernünftigen Idee. Womöglich kann ich auf
    dem Wege auch ein paar Optimierungen einbauen? Irgendwann mal.
