# -*- mode: org; coding: utf-8; -*-
# Time-stamp: <2017-10-31 22:52:02 krylon>


* kryLisp
** README
   Somebody much wiser than me once said:
   "Any sufficiently complicated C or Fortran program contains an
   ad-hoc, informally-specified, bug-ridden, slow implementation of
   half of Common Lisp."

   Somebody else, also wiser than me, added:
   "...including Common Lisp."

   So yeah, here we are. This is the mandatory toy Lisp interpreter
   everyone tried to build once in their lifetime.
   It takes ideas ideas both from Common Lisp and from Scheme, puts
   them together in a bag and beats the ____ out of them with a
   baseball bat.

   This interpreter was mainly written as an excercise to learn about
   the challenges and pitfalls one encounters when building an
   interpreter for a custom programming language - Lisp being the
   simples possible case, where the syntax is concerned -, and my main
   goal was to learn something, not to build a great piece of
   software. Not even to build a halfway decent piece of software.

   So if you look over this and think "Man, this sucks really hard",
   you are most likely right.

   If you want to help me make this suck slightly less hard, patches
   are thoughtfully considered. ;-)
** Parser
   Ich dachte erst, ich könnte ja beim Parser aus dem
   Go-Interpreterbuch abgucken, aber der ist für die simple Syntax,
   die Lisp braucht, eigentlich schon wieder overkill.
   Ich hatte ja schon mal einen Lisp-Interpreter in Python
   geschrieben, der funktionierte grundsätzlich gut.
   Aber da gab es auch eine sehr gute Bibliothek zum Bau von Parsern.
   In Go gibt es in der Standardbibliothek den ganzen Kram, den wohl
   auch der Go-Compiler benutzt, aber das wird entsprechend auch sehr
   Go-spezifisch sein.
   Es gibt ja auch _gocc_, das ist wohl grob äquivalent zu bison für C.
   Oder _ANTLR_. Aber das ist doch eigentlich alle overkill, oder?
   Eventuell kann ich auch mal PEG ausprobieren.
*** gocc
    Ich probiere jetzt erstmal gocc aus, das macht so beim Lesen der
    Doku einen guten Eindruck. Hat nur das Problem, das ich für die
    BNF-Dateien, die ich dafür schreiben muss, keine
    Syntax-Unterstützung von Emacs habe.
**** [2017-10-19 Do 17:39]
     gocc funktioniert für meine Anforderungen gut, solange ich keinen
     gewichtigen Grund finde, bleibe ich dabei. 
*** Funktionen
    [2017-09-10 So 02:53]
    Ich habe nach einigem Nachdenken beschlossen, Funktionen einen
    eigenen Datentypen zu geben, aber jetzt frage ich mich, an welcher
    Stelle aus einer Liste eine Funktion wird.
    Mein erster Gedanke war das im Parser unterzubringen, aber das
    wird nichts.
    Dann fiel mir ein, dass ich ja zumindest mittelfristig das Ziel
    habe Makros in den Interpreter einzubauen, und damit die sinnvoll
    sind, muss ich einmal am Anfang den AST abklappern und alle Makros
    expandieren.
    Bei der Gelegenheit könnte ich dann auch Lambda-Listen durch
    Funktions-Objekte ersetzen.
    Das klingt nach einer vernünftigen Idee. Womöglich kann ich auf
    dem Wege auch ein paar Optimierungen einbauen? Irgendwann mal.
** Interpreter
*** [2017-10-02 Mo 21:12] Lisp-1 vs. Lisp-2
    Allmählich verstehe ich diese Bemerkung von Kent Pitman, oder wem
    auch immer, über Lisp-1 vs. Lisp-2 Sprachen besser und frage mich
    langsam, ob ich mir den Scheiß antun will, einen Lisp-2-Dialekt zu
    erschaffen. Der Hauptvorteil ist, dass man eine Funktion list und
    eine lokale Variable list haben kann, was bei Funktionen wie
    mapcar und Freunden die Lesbarkeit etwas steigert.
    Der Performance-Vorteil ist in meinem Fall vermutlich irrelevant.
    Ich probiere es erstmal weiter als Lisp-2, und wenn mir das
    irgendwann zu haarig wird, muss ich noch mal schauen, in der
    naiven Hoffnung, dass ich mir bis dahin nicht zu sehr in den Fuß
    geschossen habe.
    Andererseits brauche ich ja zumindest für Makros noch einen
    weiteren Namespace... oder? Eigentlich nicht. Ist zumindest keine
    gute Idee, ich müsste klare Regeln definieren, wann ein Symbol
    eine Funktion oder ein Makro meint. Außer bei Sachen wie
    MACROEXPAND ist das so gut wie nie der Fall, glaube ich. :-/
*** [2017-09-23 Sa 14:22]
    Allmählich nähert sich der Interpreter dem Punkt, an dem er auf
    der theoretischen, abstrakten Ebene halbwegs vollständig ist.
    Ein bisschen boolsche Logik brauche ich noch.
*** [2017-10-19 Do 17:37]
    Ich habe inzwischen den Interpreter so weit, dass ein erstes
    einfaches Test-Script läuft.
    Jetzt kann ich mich nach der langen Debugging-Orgie also wieder
    daran setzen, Features hinzuzufügen.
    Makros? Richtige Zahlen? I/O? Datenstrukturen und Collections?
    Ich sollte mir das mal notieren
** Aufgaben
*** TODO [#A] Makros
*** TODO [#A] Zahlen
    Ich will gern bignum-Support und Support für Floating Point,
    eventuell, wenn es nicht zu haarig ist, auch Support für rationale
    und vielleicht für komplexe Zahlen.
*** TODO [#B] I/O
    Ist auf Dauer blöd, wenn das nicht geht.
*** TODO [#C] Datenstrukturen und Collections
