/* Time-stamp: <2017-12-08 19:37:18 krylon>
 * Lexical elements
 *
 * Mittwoch, 06. 09. 2017, 13:49
 * Ein Vorteil von Lisp ist, dass die Syntax so einfach ist.
 * Wenn ich Makros einbauen will, wird es ein wenig komplexer,
 * aber eins nach dem Anderen.
 *
 * Dienstag, 28. 11. 2017, 15:46
 * Jetzt komme ich langsam bei Makros an.
 * Aber wenn ich mir anschaue, wie ich das damals in Python gelöst habe,
 * sollte das so schwer nicht sein.
 * Wobei ich damals das große Glück hatte, dass diese Parser-Bibliothek,
 * die ich benutzt habe, extrem komfortabel war.
 *
 * Mittwoch, 29. 11. 2017, 18:08
 * I wonder if I am doing it wrong. I am trying to push as much of the
 * macro-processing logic into the parser.
 * Which has its advantages - any kind of error I can catch in the parser
 * I will not have to worry about in the interpreter.
 * Then again, the parser's idea of "error handling" currently is to throw its
 * hands in the air and barf.
 * And adding macros makes very little sense if I have to expand macros at "
 * runtime". My current plan is to use a two-pass scheme, where the first pass
 * handles macro-expansion (and, possibly, some rudimentary optimizations), and
 * the second pass actually interprets the code.
 * So I could do all of the macro-syntax handling in the first pass.
 * In that case, I could make the parser a lot simpler. Which would help if I
 * were to replace my current parser with goparsec.
 *
 * Donnerstag, 07. 12. 2017, 17:56
 * Even with less of the macro processing itself left out of the grammar,
 * it does not really work. My very simple first test case fails.
 */

_digit : '0'-'9' ;
integer : '0' | '1'-'9' {_digit} ;

_octaldigit : '0'-'7' ;
octalnumber : '0' _octaldigit {_octaldigit} ;


_dot: '.' ;

float: _digit {_digit} _dot _digit {_digit} 
     | _digit {_digit} 'f' ;

bignum: _digit {_digit} 'b' ;

lparen : '(' ;
rparen : ')' ;

lbracket : '[' ;
rbracket : ']' ;

lbrace : '{' ;
rbrace : '}' ;

apostrophe : '\'';
_doubleQuote : '"';

/*  Tokens für Makros
 */
atSign : '@' ;
backQuote : '`';
comma: ',' ;
colon: ':' ;


hash : '#';

_letter : 'a'-'z' | 'A'-'Z' | 'ä' | 'ö' | 'ü' | 'Ä' | 'Ö' | 'Ü' | 'ß' ;

_symbolchar : _letter | ':' | '_' | '-' | '+' | '-' | '*' | '%' | '!' | '?' | '/' | '$' | '=' | '~' | '<' | '>' | '&' ;

symbol : _symbolchar {_symbolchar} ;

string :  _doubleQuote {.} _doubleQuote ;

!whitespace : ' ' | '\t' | '\n' | '\r' ;

!comment : ';' {.} '\n' ;

/* Syntax elements */

<<
        import (
               "krylisp/token"
               "krylisp/value"
               pu "krylisp/parserutil"
               "strings"
        )
>>

Program
        : Expression                    << []value.LispValue{ $0.(value.LispValue) }, nil >>
        | Program Expression            << append($0.([]value.LispValue), $1.(value.LispValue)), nil >>
        ;

Expression
        : List
        | Array
        | Hashtable
        | Atom
        | apostrophe Expression                << &value.List{
                                                        Car: &value.ConsCell{
                                                             Car: value.Symbol("QUOTE"),
                                                             Cdr: &value.ConsCell{
                                                                  Car: $1.(value.LispValue),
                                                                  Cdr: nil,
                                                             },
                                                        },
                                                        Length: 2,
                                                  }, nil
                                                >>
        | hash Symbol                           << &value.List{
                                                        Car: &value.ConsCell{
                                                             Car: value.Symbol("FN"),
                                                             Cdr: &value.ConsCell{
                                                                  Car: $1.(value.Symbol),
                                                                  Cdr: nil,
                                                             },
                                                        },
                                                        Length: 2,
                                                   }, nil
                                                >>
        | BackquoteExpression << $0.(value.LispValue), nil >>
        ;

Atom
        : Number
        | String
        | Symbol ;

Number
        : integer                               << pu.IntValue(string($0.(*token.Token).Lit)), nil >>
        | float                                 << pu.FloatValue(string($0.(*token.Token).Lit)), nil >>
        | bignum                                << pu.Bignum(string($0.(*token.Token).Lit)), nil >>
        | octalnumber                           << pu.OctalNumber(string($0.(*token.Token).Lit)), nil >>
        ;

String 
       : string                                << pu.StringValue($0.(*token.Token).Lit), nil >>
       ;

Symbol 
       : symbol                                << value.Symbol(strings.ToUpper(string($0.(*token.Token).Lit))), nil >>
       ;

List
        : lparen ListBody rparen        << &value.List{ Car: $1.(*value.ConsCell), Length: $1.(*value.ConsCell).ActualLength() }, nil >>
        | lparen rparen                 << &value.List{ Car: nil, Length: 0 }, nil >>
        ;

ListBody
        : Expression                    << &value.ConsCell{ Car: $0.(value.LispValue) }, nil >>
        | Expression ListBody           << &value.ConsCell{ Car: $0.(value.LispValue), Cdr: $1.(*value.ConsCell) }, nil >>
        ;


Array
        : lbracket ArrayBody rbracket   << $1.(value.Array), nil >>
        | lbracket rbracket             << value.Array{}, nil >>
        ;

ArrayBody
        : Expression                    << value.Array{ $0.(value.LispValue) }, nil >>
        | ArrayBody Expression          << append($0.(value.Array), $1.(value.LispValue)), nil >>
        ;

Hashtable
        : lbrace HashBody rbrace        << $1.(value.Hashtable), nil >>
        | lbrace rbrace                 << make(value.Hashtable), nil >>
        ;

HashBody
        : Expression colon Expression        << value.Hashtable{ $0.(value.LispValue): $2.(value.LispValue), }, nil >>
        | Expression colon Expression comma HashBody << pu.HashAdd($4.(value.Hashtable), $0.(value.LispValue), $2.(value.LispValue)), nil >>
        ;

MacroExpression
        : SpliceExpression
        | UnquoteExpression
        ;

SpliceExpression
        : comma atSign Expression << &value.List{
                                        Car: &value.ConsCell{
                                             Car: value.Symbol("AT-SIGN"),
                                             Cdr: &value.ConsCell{
                                                  Car: $2.(value.LispValue),
                                             },
                                        },
                                        Length: 2,
                                     }, nil >>
        ;

UnquoteExpression
        : comma Expression << &value.List{
                                Car: &value.ConsCell{
                                     Car: value.Symbol("COMMA"),
                                     Cdr: &value.ConsCell{
                                          Car: $1.(value.LispValue),
                                     },
                                },
                                Length: 2,
                          }, nil >>
        ;

BackquoteList
        : lparen BackquoteListBody rparen << &value.List{
                                                Car: $1.(*value.ConsCell),
                                                Length: $1.(*value.ConsCell).ActualLength(),
                                             }, nil >>
        | lparen rparen << &value.List{ Length: 0 }, nil >>
        ;

BackquoteListBody
        : MacroExpression << &value.ConsCell{ Car: $0.(value.LispValue) }, nil >>
        | BackquoteExpression << &value.ConsCell{ Car: $0.(value.LispValue) }, nil >>
        | MacroExpression BackquoteListBody << &value.ConsCell{
                                                Car: $0.(value.LispValue),
                                                Cdr: $1.(*value.ConsCell),
                                               }, nil >>
        | Expression BackquoteListBody << &value.ConsCell{
                                                Car: $0.(value.LispValue),
                                                Cdr: $1.(*value.ConsCell),
                                          }, nil >>
        ;


BackquoteExpression
        : backQuote BackquoteList << &value.List{
                                        Car: &value.ConsCell{
                                             Car: value.Symbol("BACKQUOTE"),
                                             Cdr: &value.ConsCell{
                                                  Car: $1.(value.LispValue),
                                             },
                                        },
                                        Length: 2,
                                     }, nil >>
        ;

