// /home/krylon/go/src/krylisp/ast/ast.go
// -*- mode: go; coding: utf-8; -*-
// Created on 08. 09. 2017 by Benjamin Walkenhorst
// (c) 2017 Benjamin Walkenhorst
// Time-stamp: <2017-12-11 18:55:47 krylon>

// Package ast is basically a dummy package so I have some place to put tests
// for the parser (which is autogenerated at this time).
package ast
